
#include "MOTION_DEFINE.h"
#ifndef TWO_CHANNEL_MODE
#include "FAS_EziMOTIONPlusR.h"
#endif
//1-2-5. 상태 Flag 의 bit 설정

//COMMON
#define DEFAULT_PORT_NUMBER							4
#define DEFAULT_BAUDRATE							115200

#define SERVO_OFF									0
#define SERVO_ON									1


//MOTION
#define MOT_PROCESS_MAX_NUM							1
#define MOT_STATUS_MAX_NUM							3
#define MOT_STATUS_SUB_MAX_NUM						10000

#define AXIS_Y_MM4PULSE								0.001
#define AXIS_Y_PULSE4MM								1000
#define AXIS_X_MM4PULSE								0.0001
#define AXIS_X_PULSE4MM								10000
#define AXIS_Z_MM4PULSE								0.0000364
#define AXIS_Z_PULSE4MM								27475

//AXIS DEFINE
#define AXIS_Y										0
#define AXIS_X										1
#define AXIS_Z										2

#define AXIS_POS_STEP_X								0
#define AXIS_POS_STEP_Y								1
#define AXIS_POS_STEP_Z1							2
#define AXIS_POS_STEP_Z2							3


//TIME OUT
#define TIMEOUT_SAFE_SENSOR							10
#define	TIMEOUT_INPUT_BUTTON						1000
#define TIMEOUT_CYL_SENSOR							2000
#define TIMEOUT_MOTOR_STATUS						3000
#define TIMEOUT_MOTOR_MOVE							5000
#define	TIMEOUT_GRAB								3000
#define TIMEOUT_INSPECTION							5000
#define TIMEOUT_INSPECTION_TOW_CHANNEL				8000
//ALARM MESSAGE
#define ALARM_MSG_EMO								"DETECTED EMO ! (1:100)"
#define ALARM_MSG_AREA_SENSOR						"DETECTED AREA SENSOR! (1:110)"
#define ALARM_MSG_TOPCAM_STATUS						"DETECTED TOP CAM DISCONNECT! (1:120)"
#define ALARM_MSG_BOTCAM_STATUS						"DETECTED BOTTOM CAM DISCONNECT! (1:130)"

#define ALARM_MSG_MISS_START_BUTTON					"TIMEOUT, INPUT TIME OVER IN START BUTTON"
#define ALARM_MSG_AXIS_Z_STATUS						"TIMEOUT, AXIS Z STATUS FAIL(SERVO or ORIGIN)"
#define ALARM_MSG_AXIS_X_STATUS						"TIMEOUT, AXIS X STATUS FAIL(SERVO or ORIGIN)"
#define ALARM_MSG_AXIS_Y_STATUS						"TIMEOUT, AXIS Y STATUS FAIL(SERVO or ORIGIN)"
#define ALARM_MSG_AXIS_Z_MOVEFAIL					"TIMEOUT, AXIS Z MOVE FAIL"
#define ALARM_MSG_AXIS_X_MOVEFAIL					"TIMEOUT, AXIS X MOVE FAIL"
#define ALARM_MSG_AXIS_Y_MOVEFAIL					"TIMEOUT, AXIS Y MOVE FAIL"
#define ALARM_MSG_Z_CYLINDER_LEFT_DN				"TIMEOUT, LEFT Z CYLINDER DOWN"
#define ALARM_MSG_Z_CYLINDER_LEFT_UP				"TIMEOUT, LEFT Z CYLINDER UP"
#define ALARM_MSG_Z_CYLINDER_RIGHT_DN				"TIMEOUT, RIGHT Z CYLINDER DOWN"
#define ALARM_MSG_Z_CYLINDER_RIGHT_UP				"TIMEOUT, RIGHT Z CYLINDER UP"
#define ALARM_MSG_X_CYLINDER_LEFT_BK				"TIMEOUT, TOP Y CYLINDER BK"
#define ALARM_MSG_X_CYLINDER_LEFT_FW				"TIMEOUT, TOP Y CYLINDER FW"
#define ALARM_MSG_X_CYLINDER_RIGHT_BK				"TIMEOUT, RIGHT X CYLINDER BK"
#define ALARM_MSG_X_CYLINDER_RIGHT_FW				"TIMEOUT, RIGHT X CYLINDER FW"
#define ALARM_MSG_GRAB_FAIL							"TIMEOUT, GRAB FAIL"
#define ALARM_MSG_HORI_INSP_FAIL					"FAIL, HORIZONTAL INSPECTION"
#define ALARM_MSG_VERT_INSP_FAIL					"FAIL, VERTICAL INSPECTION"
#define ALARM_MSG_BARCODE_FAIL						"FAIL, BARCODE ERROR"
#define ALARM_MSG_CONTINUOUS_FAIL					"FAIL, CONTINUOUS ERROR"

#define ALARM_MSG_INSP_TIME_OUT_CHANNEL_0			"FAIL, CH NO 1, INSPECTION TIME OUT ERROR"
#define ALARM_MSG_INSP_TIME_OUT_CHANNEL_1			"FAIL, CH NO 2, INSPECTION TIME OUT ERROR"

//ALARM CODE	
#define ALARM_CODE_TOP_CAM_STATUS_CHANNEL_0			"ERR0101"
#define ALARM_CODE_BOT_CAM_STATUS_CHANNEL_0			"ERR0102"
#define ALARM_CODE_TOP_CAM_STATUS_CHANNEL_1			"ERR0103"
#define ALARM_CODE_BOT_CAM_STATUS_CHANNEL_1			"ERR0104"
#define ALARM_CODE_INSP_TIME_OUT_CHANNEL_0			"ERR0105"
#define ALARM_CODE_INSP_TIME_OUT_CHANNEL_1			"ERR0106"
//#define ALARM_CODE_EMO								"ERR0001"
//#define ALARM_CODE_AREA_SENSOR						"ERR0002"
//#define ALARM_CODE_TOPCAM_STATUS					"ERR0003"
//#define ALARM_CODE_BOTCAM_STATUS					"ERR0004"

#define ALARM_CODE_Z_CYLINDER_LEFT_DN				"ERR0010"
#define ALARM_CODE_Z_CYLINDER_LEFT_UP				"ERR0011"
#define ALARM_CODE_Z_CYLINDER_RIGHT_DN				"ERR0020"
#define ALARM_CODE_Z_CYLINDER_RIGHT_UP				"ERR0021"
#define ALARM_CODE_X_CYLINDER_LEFT_BK				"ERR0030"
#define ALARM_CODE_X_CYLINDER_LEFT_FW				"ERR0031"
#define ALARM_CODE_X_CYLINDER_RIGHT_BK				"ERR0040"
#define ALARM_CODE_X_CYLINDER_RIGHT_FW				"ERR0041"
#define ALARM_CODE_AXIS_Z_STATUS					"ERR0050"
#define ALARM_CODE_AXIS_X_STATUS					"ERR0051"
#define ALARM_CODE_AXIS_Y_STATUS					"ERR0052"
#define ALARM_CODE_AXIS_Z_MOVEFAIL					"ERR0060"
#define ALARM_CODE_AXIS_X_MOVEFAIL					"ERR0061"
#define ALARM_CODE_AXIS_Y_MOVEFAIL					"ERR0062"
#define ALARM_CODE_GRAB_FAIL						"ERR0070"
#define ALARM_CODE_MISS_START_BUTTON				"ERR0100"
#define ALARM_CODE_HORI_INSP_FAIL					"ERR0200"
#define ALARM_CODE_VERT_INSP_FAIL					"ERR0210"
#define ALARM_CODE_BARCODE_FAIL						"ERR0110"
#define ALARM_CODE_CONTINUOUS_FAIL					"ERR0150"



#define OP_EMS_CHECK								0
#define OP_AREA_SENSOR_CHECK						1

//LAMP DEFINE
#define COLOR_LAMP_RED								0
#define COLOR_LAMP_YELLOW							1
#define COLOR_LAMP_GREEN							2
#define COLOR_LAMP_OFF								3

//IO
#define MAX_OUTPUT_CNT								12
	#define OUTPUT_000_TOWER_LAMP_RED					SERVO_OUT_BITMASK_USEROUT0		// SLAVE : AXIS_0
	#define OUTPUT_001_TOWER_LAMP_YELLOW				SERVO_OUT_BITMASK_USEROUT1
	#define OUTPUT_002_TOWER_LAMP_GREEN					SERVO_OUT_BITMASK_USEROUT2
	#define OUTPUT_003_TOWER_LAMP_BUZZER				SERVO_OUT_BITMASK_USEROUT3
#ifdef TABLET
	#define OUTPUT_004_SOL_Z_CYLINDER_LEFT_UP			SERVO_OUT_BITMASK_USEROUT0		// SLAVE : AXIS_1
	#define OUTPUT_005_SOL_Z_CYLINDER_LEFT_DN			SERVO_OUT_BITMASK_USEROUT1
	#define OUTPUT_006_SOL_Z_CYLINDER_RIGHT_UP			SERVO_OUT_BITMASK_USEROUT2
	#define OUTPUT_007_SOL_Z_CYLINDER_RIGHT_DN			SERVO_OUT_BITMASK_USEROUT3
	#define OUTPUT_008_SOL_X_CYLINDER_LEFT_FW			SERVO_OUT_BITMASK_USEROUT4
	#define OUTPUT_009_SOL_X_CYLINDER_LEFT_BK			SERVO_OUT_BITMASK_USEROUT5
	#define OUTPUT_010_SOL_X_CYLINDER_RIGHT_FW			SERVO_OUT_BITMASK_USEROUT6
	#define OUTPUT_011_SOL_X_CYLINDER_RIGHT_BK			SERVO_OUT_BITMASK_USEROUT7
#else
	#define OUTPUT_004_SOL_Z_CYLINDER_LEFT_UP			SERVO_OUT_BITMASK_USEROUT1		// SLAVE : AXIS_1
	#define OUTPUT_005_SOL_Z_CYLINDER_LEFT_DN			SERVO_OUT_BITMASK_USEROUT0
	#define OUTPUT_006_SOL_Z_CYLINDER_RIGHT_UP			SERVO_OUT_BITMASK_USEROUT1
	#define OUTPUT_007_SOL_Z_CYLINDER_RIGHT_DN			SERVO_OUT_BITMASK_USEROUT2
	#define OUTPUT_008_SOL_X_CYLINDER_LEFT_FW			SERVO_OUT_BITMASK_USEROUT3
	#define OUTPUT_009_SOL_X_CYLINDER_LEFT_BK			SERVO_OUT_BITMASK_USEROUT4
	#define OUTPUT_010_SOL_X_CYLINDER_RIGHT_FW			SERVO_OUT_BITMASK_USEROUT5
	#define OUTPUT_011_SOL_X_CYLINDER_RIGHT_BK			SERVO_OUT_BITMASK_USEROUT6
#endif

#define MAX_INPUT_CNT								12
	#define INPUT_000_EMO_BUTTON						SERVO_IN_BITMASK_USERIN0		// SLAVE : AXIS_0
	#define INPUT_001_LEFT_START_BUTTON					SERVO_IN_BITMASK_USERIN1
	#define INPUT_002_RIGHT_START_BUTTON				SERVO_IN_BITMASK_USERIN2
	#define INPUT_003_AREA_SENSOR						SERVO_IN_BITMASK_USERIN3
#ifdef TABLET
	#define INPUT_004_Z_CYLINDER_LEFT_UP				SERVO_IN_BITMASK_PTA0		// SLAVE : AXIS_1
	#define INPUT_005_Z_CYLINDER_LEFT_DN				SERVO_IN_BITMASK_PTA1
	#define INPUT_006_Z_CYLINDER_RIGHT_UP				SERVO_IN_BITMASK_PTA2
	#define INPUT_007_Z_CYLINDER_RIGHT_DN				SERVO_IN_BITMASK_PTA3
	#define INPUT_008_X_CYLINDER_LEFT_FW				SERVO_IN_BITMASK_PTA4
	#define INPUT_009_X_CYLINDER_LEFT_BK				SERVO_IN_BITMASK_PTA5
	#define INPUT_010_X_CYLINDER_RIGHT_FW				SERVO_IN_BITMASK_PTA6
	#define INPUT_011_X_CYLINDER_RIGHT_BK				SERVO_IN_BITMASK_PTA7
#else
	#define INPUT_004_Z_CYLINDER_LEFT_UP				SERVO_IN_BITMASK_PTA0		// SLAVE : AXIS_1
	#define INPUT_005_Z_CYLINDER_LEFT_DN				SERVO_IN_BITMASK_PTA1
	#define INPUT_006_Z_CYLINDER_RIGHT_UP				SERVO_IN_BITMASK_PTA2
	#define INPUT_007_Z_CYLINDER_RIGHT_DN				SERVO_IN_BITMASK_PTA3
	#define INPUT_008_X_CYLINDER_LEFT_FW				SERVO_IN_BITMASK_PTA6
	#define INPUT_009_X_CYLINDER_LEFT_BK				SERVO_IN_BITMASK_PTA7
	#define INPUT_010_X_CYLINDER_RIGHT_FW				SERVO_IN_BITMASK_PTA4
	#define INPUT_011_X_CYLINDER_RIGHT_BK				SERVO_IN_BITMASK_PTA5
#endif
//COLOR
const COLORREF BACKGROUND_COLOR = RGB(230, 230, 230);
const COLORREF CLOUDBLUE = RGB(128, 184, 223);
const COLORREF WHITE = RGB(255, 255, 255);
const COLORREF BLACK = RGB(1, 1, 1);
const COLORREF DKGRAY = RGB(128, 128, 128);
const COLORREF LTGRAY = RGB(192, 192, 192);
const COLORREF LTYELLOW = RGB(255, 255, 128);
const COLORREF YELLOW = RGB(255, 255, 0);
const COLORREF DKYELLOW = RGB(128, 128, 0);
const COLORREF RED = RGB(255, 0, 0);
const COLORREF DKRED = RGB(128, 0, 0);
const COLORREF BLUE = RGB(0, 0, 255);
const COLORREF DKBLUE = RGB(0, 0, 220);
const COLORREF CYAN = RGB(0, 255, 255);
const COLORREF DKCYAN = RGB(0, 128, 128);
const COLORREF GREEN = RGB(0, 255, 0);
const COLORREF DKGREEN = RGB(0, 128, 0);
const COLORREF MAGENTA = RGB(255, 0, 255);
const COLORREF DKMAGENTA = RGB(128, 0, 128);
const COLORREF BASIC = RGB(212, 208, 200);
const COLORREF ORANGE = RGB(200, 200, 0);
const COLORREF LTSKYBLUE = RGB(128, 255, 255);
const COLORREF LTVIOLET = RGB(157, 157, 255);
const COLORREF DATA_ITEM_CHANGE_BACKGROUND_COLOR = CYAN;
const COLORREF DATA_ITEM_CHANGE_TEXT_COLOR = BLACK;
const COLORREF DATA_ITEM_TEXT_COLOR = BLACK;
const COLORREF DATA_ITEM_BACKGROUND_COLOR = CYAN;

